# Dictionary containing stadium abbreviations

stadiums_dict = {'stadium':["LAA", "HOU","OAK","TOR","ATL",
							"MIL","STL","CHC","ARI","LAD",
							"SF","CLE","SEA","MIA","NYM",
							"WSH","BAL","SD","PHI","PIT",
							"TEX","TB","BOS","CIN","COL",
							"KC","DET","MIN","CWS","NYY"]}      

bsavant_null_dict = {"pitch_type": "null", "game_date": "null", "release_speed": "null",
                      "release_pos_x": "null", "release_pos_z": "null", "player_name": "null",
                      "batter": "null", "pitcher": "null", "events": "null",
                      "description": "null", "spin_dir": "null", "spin_rate_deprecated": "null",
                      "break_angle_deprecated": "null", "break_length_deprecated": "null", "zone": "null",
                      "des": "null", "game_type": "null", "stand": "null",
                      "p_throws": "null", "home_team": "null", "away_team": "null",
                      "type": "null", "hit_location": "null", "bb_type": "null",
                      "balls": "null", "strikes": "null", "game_year": "null", 
                      "pfx_x": "null", "pfx_z": "null", "plate_x": "null",
                      "plate_z": "null", "on_3b": "null", "on_2b": "null", 
                      "on_1b": "null", "outs_when_up": "null", "inning": "null",
                      "inning_topbot": "null",
                      "hc_x": "null", "hc_y": "null", "tfs_deprecated": "null", 
                      "tfs_zulu_deprecated": "null", "fielder_2": "null", "umpire": "null", 
                      "sv_id": "null", "vx0": "null", "vy0": "null", 
                      "vz0": "null", "ax": "null", "ay": "null", 
                      "az": "null", "sz_top": "null", "sz_bot": "null", 
                      "hit_distance_sc": "null", "launch_speed": "null", "launch_angle": "null", 
                      "effective_speed": "null", "release_spin_rate": "null", "release_extension": "null", 
                      "game_pk": "null", "pitcher.1": "null", "fielder_2.1": "null", 
                      "fielder_3": "null", "fielder_4": "null", "fielder_5": "null", 
                      "fielder_6": "null", "fielder_7": "null", "fielder_8": "null", 
                      "fielder_9": "null", "release_pos_y": "null", "estimated_ba_using_speedangle": "null", 
                      "estimated_woba_using_speedangle": "null", "woba_value": "null", "woba_denom": "null", 
                      "babip_value": "null", "iso_value": "null", "launch_speed_angle": "null",
                      "at_bat_number": "null", "pitch_number": "null", "pitch_name": "null", 
                      "home_score": "null", "away_score": "null", "bat_score": "null", 
                      "fld_score": "null", "post_away_score": "null", "post_home_score": "null", 
                      "post_bat_score": "null", "post_fld_score": "null", "if_fielding_alignment": "null", 
                      "of_fielding_alignment": "null"}